name: Reusable workflow to run smoke tests on ARM64

on:
  workflow_call:

jobs:
  smoke-tests-ARM64:
    name: ARM64
    concurrency: arm-smoke-tests
    uses: kedacore/keda/.github/workflows/template-smoke-tests.yml@main
    with:
      runs-on: ARM64
      kubernetesVersion: v1.29
      kindImage: kindest/node:v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570
